#!/usr/bin/env python
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
#
# The MIT License (MIT)
# 
# Copyright (c) 2014 Chris Luke <chrisy@flirble.org>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.
# 
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.
# 
"""
PTP Mesh Server
"""

import ptptest, argparse

global debug
debug = False


if __name__ == "__main__":
    p = argparse.ArgumentParser(description="PTP Mesh Server")
    p.add_argument('-s', '--server', metavar='<address>', type=str,
            help="The address to bind to for the server", default="0.0.0.0")
    p.add_argument('-p', '--port', metavar='<port>', type=int,
            help="The port to use for the server", default=23456)
    p.add_argument('--stun', action='store_true', help="Use STUN")

    p.add_argument('-d', '--debug', action='store_true', help="Enable debugging output")
    p.add_argument('--hexdump', action='store_true', help="Enable hexdump debugging output")
    p.add_argument('--curses', action='store_true', help="Force use of curses")

    args = p.parse_args()
    debug = args.debug
    server = ptptest.Server(args)
    server.run()
